### ISSUE TITLE
pod 无法搜索到 pod 配置文件有错误

### ISSUE THREAD

**Issue by yuditxj** [zhengwenming/RCIM#2]

**Comment by zhengwenming** [comment]
这是个融云IM的demo，不能用pod集成到你自己的项目中，如果需要集成，那么看懂项目，然后copy代码和登录逻辑。（有一些类封装了，可以直接copy过去项目用，有些逻辑，比如登录，可以自己copy我的代码到你的登录事件中，布置一下即可）。
