### ISSUE TITLE
自己想写个demo, 必须得通过服务器请求token吗?

### ISSUE THREAD

**Issue by TianXiaoBei** [zhengwenming/RCIM#3]
我搞的是ios开发
想写个demo 集成下试试,
按照文档直接卡在链接服务器那步了
init完了之后链接融云服务器需要一个token
这token必须从服务器获得?
这什么逻辑啊?

**Comment by zhengwenming** [comment]
看文章，已经给了关于token的很详细的解答了。
答案很明了，测试或者demo，直接写死token（从融云后台拿token，我的demo是写死的token）；
做项目用后台的接口获取（用后台人员开发的一个专门的接口获取token）

下面是文章的摘要：
token怎么获取，哪里去获取？token的获取是要自己公司的后台提供一个获取融云token的专门接口，自己的后台开发人员去看文档做接口，后台相关事情这里不做解答（一句话：让后台人员去看融云开发文档）。

**Comment by TianXiaoBei** [comment]
嗯 谢谢您的回答 
后来才发现 测试的Token从网站获取
